# Define the list of URLs for the Debian packages
$packageUrls = @(
    'https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz'
    'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.6.9-1_amd64.deb'
    'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_24.0.5-1~ubuntu.20.04~focal_amd64.deb'
    'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_24.0.5-1~ubuntu.20.04~focal_amd64.deb'
    'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-buildx-plugin_0.11.2-1~ubuntu.20.04~focal_amd64.deb'
    'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-compose-plugin_2.6.0~ubuntu-focal_amd64.deb'
    'https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/n/nss/libnss3_3.49.1-1ubuntu1.9_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9.9_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/libgcc-s1_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/gcc-10-base_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/libasound2-data_1.2.2-2.1ubuntu2.5_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/avahi/libavahi-client3_0.7-4ubuntu7.2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/avahi/libavahi-common3_0.7-4ubuntu7.2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/avahi/libavahi-common-data_0.7-4ubuntu7.2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/e/expat/libexpat1_2.2.9-1ubuntu0.6_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/libp/libpng1.6/libpng16-16_1.6.37-2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g_1.2.11.dfsg-2ubuntu1.5_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.10.1-2ubuntu0.3_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.0.3-0ubuntu1.20.04.3_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/shadow/login_4.8.1-1ubuntu5.20.04.4_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/c/cached-property/python3-cached-property_1.5.1-4_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/setuptools/python3-pkg-resources_45.2.0-1ubuntu0.1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/p/python-docker/python3-docker_4.1.0-1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/r/requests/python3-requests_2.22.0-2ubuntu1.1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-certifi/python3-certifi_2019.11.28-1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20230311ubuntu0.20.04.1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.19_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9.9_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/libgcc-s1_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/gcc-10-base_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/d/dockerpty/python3-dockerpty_0.4.1-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/six/python3-six_1.14.0-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/d/docopt/python3-docopt_0.6.2-2.2ubuntu1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-jsonschema/python3-jsonschema_3.2.0-0ubuntu2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-attrs/python3-attr_19.3.0-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/t/texttable/python3-texttable_1.6.2-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/w/websocket-client/python3-websocket_0.53.0-2ubuntu1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/pyyaml/python3-yaml_5.3.1-1ubuntu0.1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/liby/libyaml/libyaml-0-2_0.2.2-1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-distutils_3.8.10-0ubuntu1~20.04_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.8.10-0ubuntu1~20.04_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/d/debconf/debconf_1.5.73_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-idna/python3-idna_2.8-1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-zipp/python3-zipp_1.0.0-1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/m/more-itertools/python3-more-itertools_4.2.0-1build1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/b/bzip2/bzip2_1.0.8-2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/b/bzip2/libbz2-1.0_1.0.8-2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9.9_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/libgcc-s1_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/gcc-10-base_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20230311ubuntu0.20.04.1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.19_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/d/debconf/debconf_1.5.73_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/c/cached-property/python3-cached-property_1.5.1-4_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/setuptools/python3-pkg-resources_45.2.0-1ubuntu0.1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/adduser/adduser_3.118ubuntu2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/shadow/passwd_4.8.1-1ubuntu5.20.04.4_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/audit/libaudit1_2.8.5-2ubuntu6_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/audit/libaudit-common_2.8.5-2ubuntu6_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/d/dpkg-awk/dpkg-awk_1.2+nmu2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/f/findutils/findutils_4.7.0-1ubuntu1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/grep/grep_3.4-1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/t/texinfo/install-info_6.7.0.dfsg.2-5_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/libs/libselinux/libselinux1_3.0-1build2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/pcre2/libpcre2-8-0_10.34-7ubuntu0.1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/p/pbzip2/pbzip2_1.1.13-1build1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/libstdc++6_10.5.0-1ubuntu1~20.04_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/sed/sed_4.7-1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_245.4-4ubuntu3.22_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/acl/libacl1_2.2.53-6_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/u/util-linux/util-linux_2.34-0.1ubuntu9.4_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/shadow/login_4.8.1-1ubuntu5.20.04.4_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/r/runc/runc_1.1.4-0ubuntu1~20.04.3_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/libs/libseccomp/libseccomp2_2.5.1-1ubuntu1~20.04.2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/i/iptables/libip4tc2_1.8.4-3ubuntu2.1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/a/argon2/libargon2-1_0~20171227-0.2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev1_245.4-4ubuntu3.22_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/g/gmp/libgmp10_6.2.0+dfsg-4ubuntu0.1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/libu/libunistring/libunistring2_0.9.10-2_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/x/xz-utils/liblzma5_5.2.4-1ubuntu1.1_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/u/util-linux/libblkid1_2.34-0.1ubuntu9.4_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/pam/libpam-modules_1.3.1-5ubuntu4.6_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/libs/libsemanage/libsemanage-common_3.0-1build2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libsystemd0_245.4-4ubuntu3.22_amd64.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.8.10-0ubuntu1~20.04_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/r/requests/python3-requests_2.22.0-2ubuntu1.1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-certifi/python3-certifi_2019.11.28-1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/s/six/python3-six_1.14.0-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/d/docopt/python3-docopt_0.6.2-2.2ubuntu1_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-attrs/python3-attr_19.3.0-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/universe/t/texttable/python3-texttable_1.6.2-2_all.deb'
    'http://us.archive.ubuntu.com/ubuntu/pool/main/liby/libyaml/libyaml-0-2_0.2.2-1_amd64.deb'
    'http://repo.codelogic.com/debian/all/codelogic_23.12.7_all.deb'
)

# Specify the directory where the packages will be downloaded
$downloadDir = "C:\YOUR_PATH_HERE"

# Create the download directory if it doesn't exist
if (-Not (Test-Path -Path $downloadDir -PathType Container)) {
    New-Item -ItemType Directory -Path $downloadDir | Out-Null
}

# Download each package from the list of URLs
foreach ($url in $packageUrls) {
    $fileName = [System.IO.Path]::GetFileName($url)
    $outputPath = Join-Path -Path $downloadDir -ChildPath $fileName
    Write-Host "Downloading: $url"
    Invoke-WebRequest -Uri $url -OutFile $outputPath
}

Write-Host "All packages downloaded successfully."
